import os

# ----------------------
# OpenAI Configuration
# ----------------------
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "API Key here")

# ----------------------
# MSSQL Configuration
# ----------------------
DB_CONFIG = {
    "DRIVER": "{ODBC Driver 17 for SQL Server}",
    "SERVER": "localhost\\SQLEXPRESS",
    "DATABASE": "DemoDB",
    "UID": "sa",
    "PWD": "your password here"
}

# ----------------------
# Paths
# ----------------------
USER_THREAD_FILE = "data/user_threads.json"


ASSISTANT_ID = "your assistant ID here" #Generated by running assistant_one_time.py once
